
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.Monobjc.Gui
{
	public partial class ImplementProtocolDialog
	{
		private global::Gtk.VBox vbox;
		private global::Gtk.Label labelProtocols;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.TreeView treeviewProtocols;
		private global::Gtk.Label labelMembers;
		private global::Gtk.ScrolledWindow scrolledwindow2;
		private global::Gtk.TreeView treeviewMembers;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.Monobjc.Gui.ImplementProtocolDialog
			this.Name = "MonoDevelop.Monobjc.Gui.ImplementProtocolDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Implement Protocol");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("monobjc-32.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child MonoDevelop.Monobjc.Gui.ImplementProtocolDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox = new global::Gtk.VBox ();
			this.vbox.Name = "vbox";
			this.vbox.Spacing = 6;
			this.vbox.BorderWidth = ((uint)(6));
			// Container child vbox.Gtk.Box+BoxChild
			this.labelProtocols = new global::Gtk.Label ();
			this.labelProtocols.Name = "labelProtocols";
			this.labelProtocols.Xalign = 0F;
			this.labelProtocols.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Available Protocols</b>");
			this.labelProtocols.UseMarkup = true;
			this.vbox.Add (this.labelProtocols);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox [this.labelProtocols]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.treeviewProtocols = new global::Gtk.TreeView ();
			this.treeviewProtocols.CanFocus = true;
			this.treeviewProtocols.Name = "treeviewProtocols";
			this.scrolledwindow1.Add (this.treeviewProtocols);
			this.vbox.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox [this.scrolledwindow1]));
			w4.Position = 1;
			// Container child vbox.Gtk.Box+BoxChild
			this.labelMembers = new global::Gtk.Label ();
			this.labelMembers.Name = "labelMembers";
			this.labelMembers.Xalign = 0F;
			this.labelMembers.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Protocol Members</b>");
			this.labelMembers.UseMarkup = true;
			this.vbox.Add (this.labelMembers);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox [this.labelMembers]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			this.treeviewMembers = new global::Gtk.TreeView ();
			this.treeviewMembers.CanFocus = true;
			this.treeviewMembers.Name = "treeviewMembers";
			this.scrolledwindow2.Add (this.treeviewMembers);
			this.vbox.Add (this.scrolledwindow2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox [this.scrolledwindow2]));
			w7.Position = 3;
			w1.Add (this.vbox);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox]));
			w8.Position = 0;
			// Internal child MonoDevelop.Monobjc.Gui.ImplementProtocolDialog.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "dialog1_ActionArea";
			w9.Spacing = 10;
			w9.BorderWidth = ((uint)(5));
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.buttonCancel]));
			w10.Expand = false;
			w10.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9 [this.buttonOk]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 500;
			this.DefaultHeight = 400;
			this.Show ();
		}
	}
}
