
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.Monobjc.Gui
{
	public partial class MonobjcDeploymentOptionsWidget
	{
		private global::Gtk.Table table1;
		private global::Gtk.CheckButton checkbuttonPackage;
		private global::Gtk.ComboBox comboboxArch;
		private global::Gtk.ComboBox comboboxPackagingCertificates;
		private global::Gtk.ComboBox comboboxSigningCertificates;
		private global::Gtk.HBox hbox4;
		private global::Gtk.ScrolledWindow scrolledwindowAdditionnalAssemblies;
		private global::Gtk.TreeView treeviewAdditionnalAssemblies;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Button buttonAddAdditionnalAssemblies;
		private global::Gtk.Button buttonRemoveAdditionnalAssemblies;
		private global::Gtk.HBox hbox5;
		private global::Gtk.ScrolledWindow scrolledwindowExcludedAssemblies;
		private global::Gtk.TreeView treeviewExcludedAssemblies;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Button buttonAddExcludedAssemblies;
		private global::Gtk.Button buttonRemoveExcludedAssemblies;
		private global::Gtk.HBox hbox6;
		private global::Gtk.ScrolledWindow scrolledwindowAdditionnalLibraries;
		private global::Gtk.TreeView treeviewAdditionnalLibraries;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Button buttonAddAdditionnalLibraries;
		private global::Gtk.Button buttonRemoveAdditionnalLibraries;
		private global::Gtk.Label labelAdditionnalAssemblies;
		private global::Gtk.Label labelAdditionnalLibraries;
		private global::Gtk.Label labelArch;
		private global::Gtk.Label labelExcludedAssemblies;
		private global::Gtk.Label labelFrameworks;
		private global::Gtk.Label labelPackagingCertificate;
		private global::Gtk.Label labelSigningCertificate;
		private global::Gtk.ScrolledWindow scrolledwindowFrameworks;
		private global::Gtk.TreeView treeviewEmbeddedFrameworks;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.Monobjc.Gui.MonobjcDeploymentOptionsWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.Monobjc.Gui.MonobjcDeploymentOptionsWidget";
			// Container child MonoDevelop.Monobjc.Gui.MonobjcDeploymentOptionsWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(13)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.checkbuttonPackage = new global::Gtk.CheckButton ();
			this.checkbuttonPackage.CanFocus = true;
			this.checkbuttonPackage.Name = "checkbuttonPackage";
			this.checkbuttonPackage.Label = global::Mono.Unix.Catalog.GetString ("Generate a Package");
			this.checkbuttonPackage.DrawIndicator = true;
			this.checkbuttonPackage.UseUnderline = true;
			this.table1.Add (this.checkbuttonPackage);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.checkbuttonPackage]));
			w1.TopAttach = ((uint)(2));
			w1.BottomAttach = ((uint)(3));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboboxArch = global::Gtk.ComboBox.NewText ();
			this.comboboxArch.Name = "comboboxArch";
			this.table1.Add (this.comboboxArch);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.comboboxArch]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboboxPackagingCertificates = global::Gtk.ComboBox.NewText ();
			this.comboboxPackagingCertificates.Name = "comboboxPackagingCertificates";
			this.table1.Add (this.comboboxPackagingCertificates);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.comboboxPackagingCertificates]));
			w3.TopAttach = ((uint)(3));
			w3.BottomAttach = ((uint)(4));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboboxSigningCertificates = global::Gtk.ComboBox.NewText ();
			this.comboboxSigningCertificates.Name = "comboboxSigningCertificates";
			this.table1.Add (this.comboboxSigningCertificates);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.comboboxSigningCertificates]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.scrolledwindowAdditionnalAssemblies = new global::Gtk.ScrolledWindow ();
			this.scrolledwindowAdditionnalAssemblies.CanFocus = true;
			this.scrolledwindowAdditionnalAssemblies.Name = "scrolledwindowAdditionnalAssemblies";
			this.scrolledwindowAdditionnalAssemblies.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindowAdditionnalAssemblies.Gtk.Container+ContainerChild
			this.treeviewAdditionnalAssemblies = new global::Gtk.TreeView ();
			this.treeviewAdditionnalAssemblies.CanFocus = true;
			this.treeviewAdditionnalAssemblies.Name = "treeviewAdditionnalAssemblies";
			this.scrolledwindowAdditionnalAssemblies.Add (this.treeviewAdditionnalAssemblies);
			this.hbox4.Add (this.scrolledwindowAdditionnalAssemblies);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.scrolledwindowAdditionnalAssemblies]));
			w6.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.buttonAddAdditionnalAssemblies = new global::Gtk.Button ();
			this.buttonAddAdditionnalAssemblies.CanFocus = true;
			this.buttonAddAdditionnalAssemblies.Name = "buttonAddAdditionnalAssemblies";
			this.buttonAddAdditionnalAssemblies.UseUnderline = true;
			// Container child buttonAddAdditionnalAssemblies.Gtk.Container+ContainerChild
			global::Gtk.Alignment w7 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w8 = new global::Gtk.HBox ();
			w8.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w8.Add (w9);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w11 = new global::Gtk.Label ();
			w11.LabelProp = global::Mono.Unix.Catalog.GetString ("Add");
			w11.UseUnderline = true;
			w8.Add (w11);
			w7.Add (w8);
			this.buttonAddAdditionnalAssemblies.Add (w7);
			this.vbox3.Add (this.buttonAddAdditionnalAssemblies);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.buttonAddAdditionnalAssemblies]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.buttonRemoveAdditionnalAssemblies = new global::Gtk.Button ();
			this.buttonRemoveAdditionnalAssemblies.CanFocus = true;
			this.buttonRemoveAdditionnalAssemblies.Name = "buttonRemoveAdditionnalAssemblies";
			this.buttonRemoveAdditionnalAssemblies.UseUnderline = true;
			// Container child buttonRemoveAdditionnalAssemblies.Gtk.Container+ContainerChild
			global::Gtk.Alignment w16 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w17 = new global::Gtk.HBox ();
			w17.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w18 = new global::Gtk.Image ();
			w18.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w17.Add (w18);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w20 = new global::Gtk.Label ();
			w20.LabelProp = global::Mono.Unix.Catalog.GetString ("Remove");
			w20.UseUnderline = true;
			w17.Add (w20);
			w16.Add (w17);
			this.buttonRemoveAdditionnalAssemblies.Add (w16);
			this.vbox3.Add (this.buttonRemoveAdditionnalAssemblies);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.buttonRemoveAdditionnalAssemblies]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			this.hbox4.Add (this.vbox3);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox3]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.table1.Add (this.hbox4);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox4]));
			w26.TopAttach = ((uint)(7));
			w26.BottomAttach = ((uint)(8));
			w26.RightAttach = ((uint)(2));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.scrolledwindowExcludedAssemblies = new global::Gtk.ScrolledWindow ();
			this.scrolledwindowExcludedAssemblies.CanFocus = true;
			this.scrolledwindowExcludedAssemblies.Name = "scrolledwindowExcludedAssemblies";
			this.scrolledwindowExcludedAssemblies.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindowExcludedAssemblies.Gtk.Container+ContainerChild
			this.treeviewExcludedAssemblies = new global::Gtk.TreeView ();
			this.treeviewExcludedAssemblies.CanFocus = true;
			this.treeviewExcludedAssemblies.Name = "treeviewExcludedAssemblies";
			this.scrolledwindowExcludedAssemblies.Add (this.treeviewExcludedAssemblies);
			this.hbox5.Add (this.scrolledwindowExcludedAssemblies);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.scrolledwindowExcludedAssemblies]));
			w28.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.buttonAddExcludedAssemblies = new global::Gtk.Button ();
			this.buttonAddExcludedAssemblies.CanFocus = true;
			this.buttonAddExcludedAssemblies.Name = "buttonAddExcludedAssemblies";
			this.buttonAddExcludedAssemblies.UseUnderline = true;
			// Container child buttonAddExcludedAssemblies.Gtk.Container+ContainerChild
			global::Gtk.Alignment w29 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w30 = new global::Gtk.HBox ();
			w30.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w31 = new global::Gtk.Image ();
			w31.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w30.Add (w31);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w33 = new global::Gtk.Label ();
			w33.LabelProp = global::Mono.Unix.Catalog.GetString ("Add");
			w33.UseUnderline = true;
			w30.Add (w33);
			w29.Add (w30);
			this.buttonAddExcludedAssemblies.Add (w29);
			this.vbox4.Add (this.buttonAddExcludedAssemblies);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.buttonAddExcludedAssemblies]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.buttonRemoveExcludedAssemblies = new global::Gtk.Button ();
			this.buttonRemoveExcludedAssemblies.CanFocus = true;
			this.buttonRemoveExcludedAssemblies.Name = "buttonRemoveExcludedAssemblies";
			this.buttonRemoveExcludedAssemblies.UseUnderline = true;
			// Container child buttonRemoveExcludedAssemblies.Gtk.Container+ContainerChild
			global::Gtk.Alignment w38 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w39 = new global::Gtk.HBox ();
			w39.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w40 = new global::Gtk.Image ();
			w40.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w39.Add (w40);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w42 = new global::Gtk.Label ();
			w42.LabelProp = global::Mono.Unix.Catalog.GetString ("Remove");
			w42.UseUnderline = true;
			w39.Add (w42);
			w38.Add (w39);
			this.buttonRemoveExcludedAssemblies.Add (w38);
			this.vbox4.Add (this.buttonRemoveExcludedAssemblies);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.buttonRemoveExcludedAssemblies]));
			w46.Position = 1;
			w46.Expand = false;
			w46.Fill = false;
			this.hbox5.Add (this.vbox4);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox4]));
			w47.Position = 1;
			w47.Expand = false;
			w47.Fill = false;
			this.table1.Add (this.hbox5);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox5]));
			w48.TopAttach = ((uint)(9));
			w48.BottomAttach = ((uint)(10));
			w48.RightAttach = ((uint)(2));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.scrolledwindowAdditionnalLibraries = new global::Gtk.ScrolledWindow ();
			this.scrolledwindowAdditionnalLibraries.CanFocus = true;
			this.scrolledwindowAdditionnalLibraries.Name = "scrolledwindowAdditionnalLibraries";
			this.scrolledwindowAdditionnalLibraries.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindowAdditionnalLibraries.Gtk.Container+ContainerChild
			this.treeviewAdditionnalLibraries = new global::Gtk.TreeView ();
			this.treeviewAdditionnalLibraries.CanFocus = true;
			this.treeviewAdditionnalLibraries.Name = "treeviewAdditionnalLibraries";
			this.scrolledwindowAdditionnalLibraries.Add (this.treeviewAdditionnalLibraries);
			this.hbox6.Add (this.scrolledwindowAdditionnalLibraries);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.scrolledwindowAdditionnalLibraries]));
			w50.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.buttonAddAdditionnalLibraries = new global::Gtk.Button ();
			this.buttonAddAdditionnalLibraries.CanFocus = true;
			this.buttonAddAdditionnalLibraries.Name = "buttonAddAdditionnalLibraries";
			this.buttonAddAdditionnalLibraries.UseUnderline = true;
			// Container child buttonAddAdditionnalLibraries.Gtk.Container+ContainerChild
			global::Gtk.Alignment w51 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w52 = new global::Gtk.HBox ();
			w52.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w53 = new global::Gtk.Image ();
			w53.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w52.Add (w53);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w55 = new global::Gtk.Label ();
			w55.LabelProp = global::Mono.Unix.Catalog.GetString ("Add");
			w55.UseUnderline = true;
			w52.Add (w55);
			w51.Add (w52);
			this.buttonAddAdditionnalLibraries.Add (w51);
			this.vbox5.Add (this.buttonAddAdditionnalLibraries);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.buttonAddAdditionnalLibraries]));
			w59.Position = 0;
			w59.Expand = false;
			w59.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.buttonRemoveAdditionnalLibraries = new global::Gtk.Button ();
			this.buttonRemoveAdditionnalLibraries.CanFocus = true;
			this.buttonRemoveAdditionnalLibraries.Name = "buttonRemoveAdditionnalLibraries";
			this.buttonRemoveAdditionnalLibraries.UseUnderline = true;
			// Container child buttonRemoveAdditionnalLibraries.Gtk.Container+ContainerChild
			global::Gtk.Alignment w60 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w61 = new global::Gtk.HBox ();
			w61.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w62 = new global::Gtk.Image ();
			w62.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w61.Add (w62);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w64 = new global::Gtk.Label ();
			w64.LabelProp = global::Mono.Unix.Catalog.GetString ("Remove");
			w64.UseUnderline = true;
			w61.Add (w64);
			w60.Add (w61);
			this.buttonRemoveAdditionnalLibraries.Add (w60);
			this.vbox5.Add (this.buttonRemoveAdditionnalLibraries);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.buttonRemoveAdditionnalLibraries]));
			w68.Position = 1;
			w68.Expand = false;
			w68.Fill = false;
			this.hbox6.Add (this.vbox5);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox5]));
			w69.Position = 1;
			w69.Expand = false;
			w69.Fill = false;
			this.table1.Add (this.hbox6);
			global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox6]));
			w70.TopAttach = ((uint)(11));
			w70.BottomAttach = ((uint)(12));
			w70.RightAttach = ((uint)(2));
			w70.XOptions = ((global::Gtk.AttachOptions)(4));
			w70.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelAdditionnalAssemblies = new global::Gtk.Label ();
			this.labelAdditionnalAssemblies.Name = "labelAdditionnalAssemblies";
			this.labelAdditionnalAssemblies.Xalign = 0F;
			this.labelAdditionnalAssemblies.LabelProp = global::Mono.Unix.Catalog.GetString ("Additionnal Assemblies:");
			this.table1.Add (this.labelAdditionnalAssemblies);
			global::Gtk.Table.TableChild w71 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelAdditionnalAssemblies]));
			w71.TopAttach = ((uint)(6));
			w71.BottomAttach = ((uint)(7));
			w71.RightAttach = ((uint)(2));
			w71.XOptions = ((global::Gtk.AttachOptions)(4));
			w71.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelAdditionnalLibraries = new global::Gtk.Label ();
			this.labelAdditionnalLibraries.Name = "labelAdditionnalLibraries";
			this.labelAdditionnalLibraries.Xalign = 0F;
			this.labelAdditionnalLibraries.LabelProp = global::Mono.Unix.Catalog.GetString ("Additionnal Libraries:");
			this.table1.Add (this.labelAdditionnalLibraries);
			global::Gtk.Table.TableChild w72 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelAdditionnalLibraries]));
			w72.TopAttach = ((uint)(10));
			w72.BottomAttach = ((uint)(11));
			w72.RightAttach = ((uint)(2));
			w72.XOptions = ((global::Gtk.AttachOptions)(4));
			w72.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelArch = new global::Gtk.Label ();
			this.labelArch.Name = "labelArch";
			this.labelArch.Xalign = 1F;
			this.labelArch.LabelProp = global::Mono.Unix.Catalog.GetString ("Target Mac OS Architecture:");
			this.table1.Add (this.labelArch);
			global::Gtk.Table.TableChild w73 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelArch]));
			w73.XOptions = ((global::Gtk.AttachOptions)(4));
			w73.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelExcludedAssemblies = new global::Gtk.Label ();
			this.labelExcludedAssemblies.Name = "labelExcludedAssemblies";
			this.labelExcludedAssemblies.Xalign = 0F;
			this.labelExcludedAssemblies.LabelProp = global::Mono.Unix.Catalog.GetString ("Excluded Assemblies:");
			this.table1.Add (this.labelExcludedAssemblies);
			global::Gtk.Table.TableChild w74 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelExcludedAssemblies]));
			w74.TopAttach = ((uint)(8));
			w74.BottomAttach = ((uint)(9));
			w74.RightAttach = ((uint)(2));
			w74.XOptions = ((global::Gtk.AttachOptions)(4));
			w74.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelFrameworks = new global::Gtk.Label ();
			this.labelFrameworks.Name = "labelFrameworks";
			this.labelFrameworks.Xalign = 0F;
			this.labelFrameworks.LabelProp = global::Mono.Unix.Catalog.GetString ("Framework to Embed:");
			this.table1.Add (this.labelFrameworks);
			global::Gtk.Table.TableChild w75 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelFrameworks]));
			w75.TopAttach = ((uint)(4));
			w75.BottomAttach = ((uint)(5));
			w75.RightAttach = ((uint)(2));
			w75.XOptions = ((global::Gtk.AttachOptions)(4));
			w75.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelPackagingCertificate = new global::Gtk.Label ();
			this.labelPackagingCertificate.Name = "labelPackagingCertificate";
			this.labelPackagingCertificate.Xalign = 1F;
			this.labelPackagingCertificate.LabelProp = global::Mono.Unix.Catalog.GetString ("Packaging Certificate:");
			this.table1.Add (this.labelPackagingCertificate);
			global::Gtk.Table.TableChild w76 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelPackagingCertificate]));
			w76.TopAttach = ((uint)(3));
			w76.BottomAttach = ((uint)(4));
			w76.XOptions = ((global::Gtk.AttachOptions)(4));
			w76.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelSigningCertificate = new global::Gtk.Label ();
			this.labelSigningCertificate.Name = "labelSigningCertificate";
			this.labelSigningCertificate.Xalign = 1F;
			this.labelSigningCertificate.LabelProp = global::Mono.Unix.Catalog.GetString ("Signing Certificate:");
			this.table1.Add (this.labelSigningCertificate);
			global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelSigningCertificate]));
			w77.TopAttach = ((uint)(1));
			w77.BottomAttach = ((uint)(2));
			w77.XOptions = ((global::Gtk.AttachOptions)(4));
			w77.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.scrolledwindowFrameworks = new global::Gtk.ScrolledWindow ();
			this.scrolledwindowFrameworks.CanFocus = true;
			this.scrolledwindowFrameworks.Name = "scrolledwindowFrameworks";
			this.scrolledwindowFrameworks.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindowFrameworks.Gtk.Container+ContainerChild
			this.treeviewEmbeddedFrameworks = new global::Gtk.TreeView ();
			this.treeviewEmbeddedFrameworks.CanFocus = true;
			this.treeviewEmbeddedFrameworks.Name = "treeviewEmbeddedFrameworks";
			this.treeviewEmbeddedFrameworks.HeadersVisible = false;
			this.scrolledwindowFrameworks.Add (this.treeviewEmbeddedFrameworks);
			this.table1.Add (this.scrolledwindowFrameworks);
			global::Gtk.Table.TableChild w79 = ((global::Gtk.Table.TableChild)(this.table1 [this.scrolledwindowFrameworks]));
			w79.TopAttach = ((uint)(5));
			w79.BottomAttach = ((uint)(6));
			w79.RightAttach = ((uint)(2));
			w79.XOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
